# Generated by Django 4.2.5 on 2023-09-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolov5_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodnutrition',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodnutrition',
            name='code',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
