# Generated by Django 4.2.5 on 2023-09-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolov5_django', '0002_uploadedimage_detection_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
