# Generated by Django 4.2.5 on 2023-09-25 01:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_food_nutrition_userfoodnutritions_nutrition_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yolov5_django', '0003_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedImage',
            new_name='Post',
        ),
    ]
