# Generated by Django 4.2.5 on 2023-09-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolov5_django', '0004_rename_uploadedimage_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_content',
            field=models.TextField(default='간단한 메모 작성 가능합니다.', max_length=255),
        ),
    ]
