# Generated by Django 4.2.5 on 2023-09-27 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolov5_django', '0006_post_day_post_hour_post_month_post_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.IntegerField(),
        ),
    ]
