# Generated by Django 4.2.5 on 2023-09-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yolov5_django', '0007_remove_post_uploaded_at_post_post_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_time',
        ),
    ]
