# Generated by Django 4.2.5 on 2023-09-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolov5_django', '0008_remove_post_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='hour',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='month',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
