# Generated by Django 4.2.5 on 2023-09-27 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolov5_django', '0009_alter_post_day_alter_post_hour_alter_post_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='day',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='post',
            name='month',
        ),
        migrations.RemoveField(
            model_name='post',
            name='year',
        ),
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
