# Generated by Django 4.2.5 on 2023-09-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolov5_django', '0010_remove_post_day_remove_post_hour_remove_post_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_content',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
