# Generated by Django 4.2.5 on 2023-09-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_height_alter_userprofile_weight'),
    ]

    operations = [
    ]
