# Generated by Django 4.2.5 on 2023-09-23 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yolov5_django', '0003_alter_uploadedimage_image'),
        ('accounts', '0006_auto_20230924_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfoodnutritions',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yolov5_django.uploadedimage'),
        ),
    ]
