# Generated by Django 4.2.5 on 2023-09-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yolov5_django', '0003_alter_uploadedimage_image'),
        ('accounts', '0007_userfoodnutritions_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfoodnutritions',
            name='carbohydrate',
        ),
        migrations.RemoveField(
            model_name='userfoodnutritions',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='userfoodnutritions',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='userfoodnutritions',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='userfoodnutritions',
            name='sodium',
        ),
        migrations.AddField(
            model_name='userfoodnutritions',
            name='food_nutrition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yolov5_django.foodnutrition'),
        ),
        migrations.AlterField(
            model_name='userfoodnutritions',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userfoodnutritions',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yolov5_django.uploadedimage'),
        ),
    ]
